server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/${user.dir}/DeepSkill/Week-4/Solution of Microservices/config-server/src/main/resources/config/
