# Spring Profile Configuration
spring.profiles.active=h2

# Spring Framework and Application Log levels
logging.level.org.springframework=info
logging.level.com.cognizant=debug

# Hibernate log SQL and parameters
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.type.descriptor.sql=trace

# Log Console Pattern
logging.pattern.console=%d{dd-MM-yy} %d{HH:mm:ss.SSS} %-20.20thread %5p %-25.25logger{25} %25M %4L %m%n
