# H2 Database configurations
spring.datasource.url=jdbc:h2:mem:ormlearndb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY,VALUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate configurations for H2
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
